on:
  push:
    branches:
    - main
jobs:
  count-lines:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
    steps:
    - name: count-lines
      run: wc -l ./actions.js > /tmp/linesofcode.txt

  send-mail:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18.x', '20.x']
    steps:
     - name: Send email
       uses: devellany/send-mailer@v1.0.2
       with:
          host: smtp.google.com
          account: ${{secrets.ACCOUNT}}
          password: ${{secrets.MAIL_PASSWORD}}
          sender: devellany
          from: ${{secrets.MAIL_ADDRESS}}
          to: devellay@dico.me
          subject: mail title.
          body: file://README.md
          contentType: text/html
          attachments: file://attachmets.json
   
